modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${github_page}"
authors="Neovitalism"
description='''
${mod_description}
'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="SERVER"
